let ALL_PRODUCTS=[]; let AGENT_HISTORY=[];
async function getProducts(){if(ALL_PRODUCTS.length)return ALL_PRODUCTS;const r=await fetch('data/products.json');ALL_PRODUCTS=await r.json();return ALL_PRODUCTS}
const money=n=>new Intl.NumberFormat('ko-KR').format(n)+'원';
function cardHTML(p){return `<a class="product-card" href="product.html?id=${encodeURIComponent(p.id)}"><div class="product-image ${p.gender==='MEN'?'men':''}"></div><div class="name">${p.name}</div><div class="price">${money(p.price)}</div><div class="meta">${(p.colors||[]).join(' · ')} · ${p.fit||''}</div></a>`}
async function loadFeatured(){const ps=await getProducts();document.getElementById('featured').innerHTML=ps.slice(0,6).map(cardHTML).join('')}
async function loadProducts(){const ps=await getProducts(),q=new URLSearchParams(location.search),gender=q.get('gender');let active=q.get('category')||'all';function render(){const list=ps.filter(p=>(!gender||p.gender===gender)&&(active==='all'||p.category===active));document.getElementById('productGrid').innerHTML=list.map(cardHTML).join('');document.getElementById('resultCount').textContent=`${list.length}개 상품`}document.querySelectorAll('#filterChips button').forEach(btn=>{if(btn.dataset.filter===active){document.querySelectorAll('#filterChips button').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected')}btn.onclick=()=>{active=btn.dataset.filter;document.querySelectorAll('#filterChips button').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');render()}});render()}
function esc(s=''){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function addUserMessage(text){const area=document.getElementById('chatArea'),el=document.createElement('div');el.className='user-msg';el.textContent=text;area.appendChild(el);area.scrollTop=area.scrollHeight}
function addAgentMessage(text,products=[]){const area=document.getElementById('chatArea'),wrap=document.createElement('div');wrap.className='agent-block';wrap.innerHTML=`<div class="agent-msg">${esc(text).replace(/\n/g,'<br>')}</div>`;if(products.length){const row=document.createElement('div');row.className='agent-products';row.innerHTML=products.map(p=>`<a class="agent-product-card" href="product.html?id=${encodeURIComponent(p.id)}"><div class="agent-product-image ${p.gender==='MEN'?'men':''}"></div><strong>${esc(p.name)}</strong><span>${money(p.price)}</span><small>${esc((p.colors||[]).join(' · '))}</small><b>상품 보기 →</b></a>`).join('');wrap.appendChild(row)}area.appendChild(wrap);area.scrollTop=area.scrollHeight}
function setLoading(on){const b=document.getElementById('sendAgent'),i=document.getElementById('agentInput');b.disabled=on;i.disabled=on;b.textContent=on?'…':'↑'}
async function sendAgentMessage(currentProductId,preset=''){const input=document.getElementById('agentInput'),text=(preset||input.value).trim();if(!text)return;input.value='';addUserMessage(text);setLoading(true);try{const r=await fetch('/api/agent',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,currentProductId,history:AGENT_HISTORY.slice(-6)})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Agent 오류');AGENT_HISTORY.push({role:'user',text});AGENT_HISTORY.push({role:'assistant',text:data.reply});addAgentMessage(data.reply,data.products||[])}catch(e){addAgentMessage(`지금 Agent를 실행하지 못했어요. ${e.message}`)}finally{setLoading(false);input.focus()}}
async function loadProductDetail(){const ps=await getProducts(),id=new URLSearchParams(location.search).get('id')||ps[0].id,p=ps.find(x=>x.id===id)||ps[0];document.getElementById('detail').innerHTML=`<div class="detail-visual"></div><section class="detail-body"><div class="brand-mini">STYLER SELECT · ${p.id}</div><h1>${p.name}</h1><div class="price-big">${money(p.price)}</div><div class="option-title">COLOR</div><div class="option-row">${(p.colors||[]).map((x,i)=>`<button class="option ${i===0?'selected':''}">${x}</button>`).join('')}</div><div class="option-title">SIZE</div><div class="option-row">${(p.sizes||[]).map((x,i)=>`<button class="option ${i===0?'selected':''}">${x}</button>`).join('')}</div><div class="ai-reason"><strong>✦ Agent가 참고할 상품 특징</strong><br/>${p.agent_notes||''}</div></section>`;const sheet=document.getElementById('agentSheet');document.getElementById('contextProduct').textContent=p.name;document.getElementById('openAgent').onclick=()=>sheet.classList.remove('hidden');document.getElementById('closeAgent').onclick=()=>sheet.classList.add('hidden');sheet.onclick=e=>{if(e.target===sheet)sheet.classList.add('hidden')};document.getElementById('sendAgent').onclick=()=>sendAgentMessage(p.id);document.getElementById('agentInput').addEventListener('keydown',e=>{if(e.key==='Enter')sendAgentMessage(p.id)});document.querySelectorAll('.quick-actions [data-prompt]').forEach(btn=>btn.onclick=()=>sendAgentMessage(p.id,btn.dataset.prompt))}
